using System;
using System.Collections.Generic;
using System.Text;
using MyLibraries.UsefulMethods;

namespace ZevviCompiler.ZI
{
    // TODO make variable numbers in ZI.Variable be auto-generated by symbol table
    public readonly struct Variable : IOperand
    {
        public readonly int number;
        public readonly VariableStorageType storageType;

        public Variable(int number, VariableStorageType storageType = VariableStorageType.Variable)
        {
            this.number = number;
            this.storageType = storageType;
        }

        public override bool Equals(object obj)
        {
            return obj is Variable variable &&
                   storageType == variable.storageType &&
                   number == variable.number;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(number, storageType);
        }

        public string ToStringSimple()
        {
            return ToStringFull();
        }

        public string ToStringFull()
        {
            return storageType switch
            {
                VariableStorageType.Variable => number < 26 ? char.ToString((char)('a' + number)) : "$" + number,
                VariableStorageType.Parameter => "param_" + number,
                VariableStorageType.Local => "local_" + (number < 26 ? char.ToString((char)('a' + number)) : number),
                VariableStorageType.Global => "global_" + (number < 26 ? char.ToString((char)('a' + number)) : number),
                _ => throw new UnknownEnumValueInternalException(nameof(VariableStorageType)),
            };
        }

        public override string ToString()
        {
            return ToStringFull();
        }

        dynamic IOperand.GetValue(Interpreter interpreter, int index)
        {
            switch (storageType)
            {
                case VariableStorageType.Variable:
                    return interpreter.Vars.GetOrAdd((number, index));
                case VariableStorageType.Parameter:
                    if (index != 0)
                    {
                        throw new ZIException($"Cannot index parameter in ZI code: param_{number}.");
                    }
                    return interpreter.Parameters.GetOrThrow(number,
                        new ZIException($"ZI parameter index out of range: {number} >= {interpreter.Parameters.Length}."));
                case VariableStorageType.Local:
                    return interpreter.LocalVars.GetOrAdd((number, index));
                case VariableStorageType.Global:
                    return interpreter.GlobalStorage.GetOrAdd((number, index));
                default:
                    throw new UnknownEnumValueInternalException(nameof(VariableStorageType));
            };
        }

        dynamic IOperand.SetValue(Interpreter interpreter, dynamic value, int index)
        {
            switch (storageType)
            {
                case VariableStorageType.Variable:
                    interpreter.Vars[(number, index)] = value;
                    break;
                case VariableStorageType.Parameter:
                    if (index != 0)
                    {
                        throw new ZIException($"Cannot index parameter in ZI code: param_{number}.");
                    }
                    if (number >= interpreter.Parameters.Length)
                    {
                        throw new ZIException($"ZI parameter index out of range: {number} >= {interpreter.Parameters.Length}.");
                    }
                    interpreter.Parameters[number] = value;
                    break;
                case VariableStorageType.Local:
                    interpreter.LocalVars[(number, index)] = value;
                    break;
                case VariableStorageType.Global:
                    interpreter.GlobalStorage[(number, index)] = value;
                    break;
                default:
                    throw new UnknownEnumValueInternalException(nameof(VariableStorageType));
            }
            return null;
        }

        public static bool operator ==(Variable left, Variable right)
        {
            return left.Equals(right);
        }

        public static bool operator !=(Variable left, Variable right)
        {
            return !(left == right);
        }
    }
}
