using System;
using System.Collections.Generic;
using System.Text;

namespace ZevviCompiler
{
    [Obsolete("Use the new ZevviCompiler.ZI namespace instead.")]
    public enum MachineInstruction
    {
        Null,
        Push,
        Pop,
        PushI,
        PopI,
        PushCon,
        StoreI,
        StoNxt,
        StoNxtI,
        Next,
        Add,
        Sub,
        Mul,
        Div,
        Mod,
        AddI,
        SubI,
        MulI,
        DivI,
        ModI,
        Neg,
        And,
        Or,
        Xor,
        Not,
        AndI,
        OrI,
        XorI,
        IsZero,
        IsPos,
        IsNeg,
        Goto,
        GotoRel,
        If,
        IfRel,
        IfNot,
        IfNotRel,
        IfPos,
        IfPosRel,
        IfNeg,
        IfNegRel,
        Call,
        CallRel,
        Return,
        GotoI,
        GotoRelI,
        IfI,
        IfRelI,
        IfNotI,
        IfNotRelI,
        IfPosI,
        IfPosRelI,
        IfNegI,
        IfNegRelI,
        CallI,
        CallRelI,
        PrgCtr,
        ClrStk,
        Swap,
        Dup,
        Remove,
        SysExec,
        Mark,
        CallMark,
        GotoMark,
        Halt
    }
}
